### ISSUE TITLE
Powers

### ISSUE THREAD

**Issue by CHillAaron** [EthanHair/mole-patrol#3]
Could have a power up every so many points that can allow different feats

1) some holes get covered up
2) Dog helps you catch moles
3) moles stay up so you can wack them

**Comment by EthanHair** [comment]
I think I'll do

- Golden Hammer: a golden hammer that auto whacks for 10 secs
- Corks: Randomly blocks 6 holes for 10 secs 

A power up will be randomly selected every 4 golden moles whacked

There will be grayed out icons for each power up that will light up when activated
